import type { Entity, Item, Location, Route, School } from '../shared/types.js';
export const canon = `《灰区：撤离》：2037年3月15日，新沪港灰区。2027年联合能源集团UEG在近海人工岛进行“湮灭”高能实验，撕开维度裂隙。半径约80公里的工业港与城镇被封锁。零号井是源头。玩家可以是居民、外来者、专业人士、负债者、逃亡者或回收者；具体身份与开局强度由玩家和主持人协商，不是命定英雄。灰币由铁壁发行，在外界几乎不值钱。
围栏镇在南缘；工业外缘有石化工厂、集装箱码头、旧药厂、军事哨站；城镇废墟有沿海小镇、商业街、警察总局、通讯站；荒野有采石场、变异生态带、高地；地下有实验室A/B和观测站；核心是零号井。
铁壁安保以合同与债务维持回收经济；黑水亚洲竞争挖角；龙盾国际经营先进装备、旧UEG地图与结晶加工；UEG仍在自动化采掘并阻止干涉。守望者是原住民，少校周若冰领导扎根派保卫社区，前UEG工程师老吕领导回归派寻找关闭裂隙的方法，灰区二代烬领导启示派探索镜界。电鳗陈占石化厂，静默叶琳在通讯站，铁心保护采石场平民。拾荒者有各自利益。镜界实体对能量敏感。
黑潮从零号井开始，以约八周向外围扩张。它是按时间变化的环境。保留人物动机；交涉、背叛、交易、避战、造物、据点、改道、调查、撤出灰区均可能，不要限定为行动模板。
异能三法则：离开区域失效，重新进入约一小时恢复；结晶须接触传导、不可徒手合成高阶；RSN超过WIL增加失控。五系为身体强化、元素共鸣、感知扩张、空间干涉、精神支配。具体能力与强度以已确认角色档案为准，须有范围、条件、限制与代价；不能变成无限资源、全知或无条件控制。S/A/B/C/D/E是同一结晶的纯度等级。枪械始终致命。`;
export const powers: Record<
  Exclude<School, 'none'>,
  { name: string; cost: number; limit: string }
> = {
  body: {
    name: '短时强化',
    cost: 2,
    limit: '接触结晶；十秒内强化一次发力，或减轻一次冲击。无法挡住步枪弹、长出肢体或消除创伤。',
  },
  element: {
    name: '共振冲击',
    cost: 3,
    limit:
      '接触结晶；最多五米，作用于一个可见目标。可扰动轻物、造成冲击；不能制造持续电源或无限护盾。',
  },
  sense: {
    name: '脉冲探测',
    cost: 2,
    limit:
      '接触结晶；半径二十米，只感到活动与能量轮廓，无法识别人名、意图、密码或精确穿透厚混凝土。',
  },
  space: {
    name: '空间感知',
    cost: 3,
    limit: '接触结晶；十米内辨认空间扭曲，短时偏转手边轻物；初阶不能瞬移、穿墙或开永久裂隙。',
  },
  mind: {
    name: '钢铁神经',
    cost: 2,
    limit: '接触结晶；稳定自己的恐惧，或接触一名自愿者协助集中注意力。不能操控他人决定或改写记忆。',
  },
};
const item = (
  id: string,
  name: string,
  quantity: number,
  weight: number,
  value: number,
  kind: Item['kind'],
  description: string,
): Item => ({ id, name, quantity, weight, value, kind, description });
export const goods: Record<string, Item> = {
  rifle: {
    ...item(
      'rifle',
      '56式半自动步枪',
      1,
      3.8,
      260,
      'weapon',
      '7.62×39毫米；旧枪，十发固定弹仓。射击会暴露位置。',
    ),
    weapon: { capacity: 10, loaded: 10, ammo: 'ammo762', damage: 3, range: 250 },
  },
  ammo762: item(
    'ammo762',
    '7.62×39毫米弹',
    30,
    0.016,
    2,
    'ammo',
    '逐发计算，装填后从散装弹药中扣除。',
  ),
  vest: item(
    'vest',
    '旧防弹背心',
    1,
    3,
    180,
    'gear',
    '仅躯干防护，受击降低一级伤势；无法覆盖四肢与头部。',
  ),
  bandage: item('bandage', '止血绷带', 3, 0.08, 12, 'medical', '一卷处理一处出血，不使伤口痊愈。'),
  medkit: item(
    'medkit',
    '医疗耗材包',
    1,
    0.5,
    65,
    'medical',
    '清创、缝合与敷料。需医疗技能和恢复时间。',
  ),
  ration: item('ration', '口粮', 3, 0.4, 15, 'food', '一份补充十二小时的食物需求。'),
  water: item('water', '饮用水 / 500 ml', 6, 0.5, 6, 'water', '一份补充四小时的饮水需求。'),
  tools: item(
    'tools',
    '多功能工具',
    1,
    0.5,
    60,
    'gear',
    '钳、刀和小型螺丝刀。可复用，不能代替焊机或电子实验室。',
  ),
  wire: item('wire', '细钢丝', 2, 0.1, 8, 'material', '每卷三米，可制作绊线、绑定和简单机关。'),
  scrap: item(
    'scrap',
    '金属零件',
    2,
    0.25,
    10,
    'material',
    '废罐、垫片与小螺栓，用途取决于加工办法。',
  ),
  crystal_c: item(
    'crystal_c',
    'C级结晶',
    1,
    0.05,
    30,
    'crystal',
    '随身导体。不能徒手合并成更高等级。',
  ),
  antibiotics: item(
    'antibiotics',
    '密封抗生素',
    4,
    0.1,
    80,
    'medical',
    '原厂密封，交给老郑前应检查有效期和污染。',
  ),
  module: item(
    'module',
    '柴油机控制模块',
    1,
    1.5,
    180,
    'evidence',
    '采石场工程机械备件，锯子需要它。',
  ),
  data: item('data', 'UEG观测记录', 1, 0.05, 500, 'evidence', '原始离线介质，需要技术人员解释。'),
};
export const stock = (key: string, quantity?: number): Item => ({
  ...structuredClone(goods[key]),
  quantity: quantity ?? goods[key].quantity,
});
const places: [string, string, number, number, number, string, boolean, number][] = [
  [
    'outside',
    '封锁线外',
    -1,
    17,
    93,
    '军方登记口。灰币兑换贬值，异能在边界外失效。离开并不解除债务。',
    false,
    0,
  ],
  [
    'town',
    '围栏镇',
    0,
    26,
    82,
    '铁皮屋顶、柴油发电机和一排关着门的车库。合同中心贴着新工单。老郑的药柜空了一半；铆钉巷的老高正在清点弹药。',
    true,
    0,
  ],
  [
    'petro',
    '石化工厂',
    1,
    15,
    64,
    '锈蚀储罐间挂着电缆。“电鳗”陈的人在收费口巡逻。维修管道通向北面的厂区。',
    false,
    2,
  ],
  [
    'dock',
    '集装箱码头',
    1,
    45,
    68,
    '潮水穿过倾斜的货柜，吊机停在半空。拾荒队占用干燥的高地，铁壁不保证这里的安全。',
    false,
    2,
  ],
  [
    'pharma',
    '旧药厂',
    1,
    33,
    58,
    '主楼断电，药库侧门锈死。排水沟通向装卸间，进去的人得自己安排退路。',
    false,
    2,
  ],
  [
    'post',
    '军事哨站',
    1,
    61,
    62,
    '废弃沙袋和一个仍亮着红灯的无人机机库。通往北面的道路布有车辆残骸。',
    false,
    3,
  ],
  [
    'coast',
    '沿海小镇',
    2,
    57,
    47,
    '海水淹过一层的房间。楼上偶尔有烟，居民不向每支持枪队伍开门。',
    true,
    2,
  ],
  [
    'market',
    '中央商业街',
    2,
    34,
    42,
    '商店卷帘被撬开；路口有人堆起路障，碎玻璃上留着新车辙。',
    false,
    3,
  ],
  [
    'police',
    '警察总局',
    2,
    24,
    34,
    '大厅被翻过，地下证物库还在。有人给侧门接了一套简陋的报警装置。',
    false,
    3,
  ],
  ['comms', '废弃通讯站', 2, 70, 39, '静默叶琳住在断裂天线下的设备间。接近前先表明身份。', true, 2],
  [
    'watch',
    '守望者前哨',
    2,
    47,
    33,
    '原住民在维修围墙。这里有家庭、菜地和内部分歧，陌生武装需要解释来意。',
    true,
    2,
  ],
  [
    'quarry',
    '旧采石场',
    3,
    19,
    25,
    '铁心守着工棚里的平民。旧推土机停在深坑边，北坡通向异常荒野。',
    true,
    3,
  ],
  [
    'wild',
    '变异生态带',
    3,
    38,
    22,
    '植物覆盖了公路，动物的迁徙方向正在改变。视线和足迹都不可靠。',
    false,
    4,
  ],
  [
    'highland',
    '开阔高地',
    3,
    66,
    23,
    '无遮蔽的高坡能看见近海人工岛。这里容易发现敌人，也容易被发现。',
    false,
    3,
  ],
  [
    'lab-a',
    '地下实验室 A 区',
    4,
    37,
    12,
    '地下应急灯仍在工作，门禁属于UEG。狭窄通道限制撤退和交叉射界。',
    false,
    4,
  ],
  [
    'lab-b',
    '地下实验室 B 区',
    4,
    54,
    13,
    '工业结晶精炼设备仍有电力。通风和供氧需要监测，机器将未授权人员视为入侵者。',
    false,
    5,
  ],
  [
    'observatory',
    '维度交汇观测站',
    4,
    74,
    13,
    '海堤下的观测设施连接零号井，数据线仍向深处传输。',
    false,
    5,
  ],
  [
    'well',
    '零号井',
    5,
    88,
    5,
    '人工岛中心的维度裂隙。低处已有黑雾，枪械不能解决这里的环境风险。',
    false,
    5,
  ],
];
export const locations: Location[] = places.map(
  ([id, name, zone, x, y, description, shelter, danger]) => ({
    id,
    name,
    zone,
    x,
    y,
    description,
    shelter,
    danger,
  }),
);
const links: [string, string, number][] = [
  ['outside', 'town', 20],
  ['town', 'petro', 25],
  ['town', 'dock', 20],
  ['town', 'pharma', 30],
  ['dock', 'post', 20],
  ['petro', 'pharma', 15],
  ['petro', 'market', 40],
  ['pharma', 'market', 35],
  ['dock', 'coast', 35],
  ['post', 'coast', 30],
  ['market', 'police', 20],
  ['market', 'coast', 30],
  ['market', 'watch', 30],
  ['coast', 'comms', 25],
  ['comms', 'watch', 30],
  ['watch', 'quarry', 50],
  ['police', 'quarry', 55],
  ['watch', 'wild', 50],
  ['comms', 'highland', 60],
  ['quarry', 'wild', 35],
  ['wild', 'highland', 40],
  ['wild', 'lab-a', 60],
  ['highland', 'observatory', 65],
  ['lab-a', 'lab-b', 30],
  ['lab-b', 'observatory', 35],
  ['observatory', 'well', 45],
];
export const routes: Route[] = links.map(([from, to, minutes]) => ({
  id: `${from}-${to}`,
  from,
  to,
  minutes,
  description: '已知步行路线；所需时间包含辨路与谨慎推进。',
}));
const person = (
  id: string,
  name: string,
  location: string,
  faction: string,
  description: string,
  secret: string,
  extra: Partial<Entity> = {},
): Entity => ({
  id,
  name,
  location,
  faction,
  description,
  secret,
  kind: 'person',
  state: '活动正常',
  visible: true,
  attitude: 0,
  health: 8,
  armor: 0,
  hostile: false,
  attack: 45,
  damage: 3,
  ammo: 20,
  cash: 500,
  inventory: [],
  merchant: false,
  nextMove: 360,
  ...extra,
});
export const entities: Entity[] = [
  person(
    'gao',
    '老高',
    'town',
    '拾荒者',
    '铆钉巷军火商。买卖枪弹与结晶，报价写在柜台边。',
    '想摆脱铁壁控制，欠锯子人情，暗中联系龙盾；不愿为了陌生人白送装备。',
    {
      merchant: true,
      inventory: [
        stock('ammo762', 150),
        stock('vest', 2),
        stock('rifle', 2),
        stock('wire', 10),
        stock('scrap', 12),
        stock('tools', 3),
      ],
    },
  ),
  person(
    'zheng',
    '老郑',
    'town',
    '独立',
    '六十一岁的外科医生。先救重伤员，医药费可以欠，药物不能凭空变出来。',
    '尊敬少校；坚持救治穷人，正在研究黑雾对神经的影响。',
    { merchant: true, inventory: [stock('bandage', 10), stock('medkit', 4)] },
  ),
  person(
    'saw',
    '锯子',
    'town',
    '独立',
    '工坊机械师，忙着修发电机，缺柴油机控制模块。',
    '想修好发电机、卖掉工坊，去灰区外找女儿。',
  ),
  person(
    'crow',
    '鸦',
    'town',
    '独立',
    '情报中介。交换消息或付钱，没有免费全知的答案。',
    '十年前妹妹失踪在灰区深处。她收集黑潮时间表，也在寻找妹妹。',
  ),
  person(
    'fang',
    '方远',
    'town',
    '铁壁安保',
    '合同官。办公桌上摆着回收报价和欠款清单。',
    '维持人手和利润，危机时优先撤出公司资产。',
    { cash: 5000 },
  ),
  person(
    'supply',
    '补给仓库',
    'town',
    '铁壁安保',
    '口粮、水和常用耗材，库存有限。',
    '黑潮逼近后供应线会收缩。',
    {
      kind: 'container',
      merchant: true,
      inventory: [stock('water', 40), stock('ration', 25)],
      attack: 0,
    },
  ),
  person(
    'castro',
    '卡斯特罗',
    'town',
    '黑水亚洲',
    '黑水招募员，正在酒馆附近找熟练回收者。',
    '愿意开更高报酬，但合同条件更苛刻。',
  ),
  person(
    'chen',
    '“电鳗”陈',
    'petro',
    '独立',
    '持有高共鸣电系异能的工厂占领者。跟班看重通行费与物资。',
    'RSN8，电力控制强但过载会伤到自己；可以交易，不会无故死战。',
    { armor: 1, inventory: [stock('crystal_c', 4)], cash: 300 },
  ),
  person(
    'scavs',
    '码头拾荒队',
    'dock',
    '拾荒者',
    '三个人躲在货柜屋顶，看着路过的人。武器没有放下。',
    '需要水和药；有人想抢夺，有人反对。缺水时将迁往商业街。',
    { armor: 1, nextMove: 720 },
  ),
  person(
    'pharma-cache',
    '药库内柜',
    'pharma',
    '无',
    '装卸间背后的密封药柜。',
    '排水沟可绕开生锈的正门。药柜可撬开或拆铰链。',
    {
      kind: 'container',
      visible: false,
      attack: 0,
      inventory: [stock('antibiotics', 4), stock('bandage', 3)],
      cash: 0,
    },
  ),
  person(
    'drone',
    '巡逻无人机',
    'post',
    'UEG',
    '低空巡逻的军用无人机，红灯扫过残骸。',
    '收到未授权目标信号即开火，电源与传感器是弱点。',
    { kind: 'machine', hostile: true, health: 6, armor: 1, attack: 50, ammo: 30 },
  ),
  person(
    'major',
    '少校 · 周若冰',
    'watch',
    '守望者',
    '守望者扎根派的实际领导者，优先考虑社区安全。',
    '共鸣正在逐渐超过控制能力。她需要可靠的接班人，不是崇拜者。',
    { armor: 1, health: 10 },
  ),
  person(
    'lu',
    '老吕',
    'watch',
    '守望者',
    '前UEG工程师，相信裂隙有办法关闭。',
    '需要地下实验室的关门数据；长期等不到援手会自行出发。',
  ),
  person(
    'jin',
    '烬',
    'watch',
    '守望者',
    '生于灰区的年轻异能者，想弄清镜界另一侧是什么。',
    '能感知黑潮中的信号，愿冒险深入，和少校、老吕存在分歧。',
  ),
  person(
    'ye',
    '“静默”叶琳',
    'comms',
    '独立',
    '高共鸣感知者，警觉但并不主动攻击访客。',
    'RSN9，躲避UEG；不愿被任何公司登记。',
  ),
  person(
    'iron',
    '“铁心”',
    'quarry',
    '独立',
    '身体强化异能者，保护采石场工棚里的平民。',
    'RSN7；可以谈判取走模块，但不允许破坏居民依赖的设备。',
    { armor: 2 },
  ),
  person(
    'engine',
    '废推土机',
    'quarry',
    '无',
    '柴油机盖布满尘土，驾驶室门敞开。',
    '控制模块尚可用，需工具拆下。',
    { kind: 'container', attack: 0, inventory: [stock('module')], cash: 0 },
  ),
  person(
    'terminal',
    'UEG离线终端',
    'lab-a',
    'UEG',
    '门禁后方的离线研究终端。',
    '记录包含关门数据的一部分；绕过供电警报或研究接口可读出。',
    { kind: 'machine', attack: 0, visible: true, inventory: [stock('data')] },
  ),
  person(
    'security',
    'UEG安保机',
    'lab-b',
    'UEG',
    '履带式安保机械封锁主通道。',
    '会追击未授权人员，可干扰传感器、绕行维修井或伪造授权。',
    { kind: 'machine', hostile: true, armor: 2, health: 10, attack: 55, ammo: 100 },
  ),
  person(
    'rift',
    '裂隙控制台',
    'well',
    'UEG',
    '高能控制台旁的仪表持续报警。',
    '关闭、控制、继续利用或进入裂隙需要不同技术与势力合作；没有预设唯一正确终局。',
    { kind: 'feature', attack: 0 },
  ),
];
